name: Maven Compile & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-build.yml@v2.3.5
    with:
      java-version: '8'
      mvn-parameters: '-P run-its -Dinvoker.streamLogsOnFailures verify'
