name: Invoker ITs

on: [push, pull_request, workflow_dispatch]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: zulu
          cache: maven

      - name: Run invoker ITs
        run: mvn --errors --batch-mode --show-version -Dinvoker.streamLogsOnFailures -P run-its verify
